version: '3.7'

services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: '${YOUR_DOMAIN_NAME}'
    ports:
      - "${GITLAB_SHELL_SSH_PORT}:22"
    volumes:
      - '${GITLAB_HOST_LOG_PATH}:/var/log/gitlab'
      - '${DATA_PATH_HOST}:/var/opt/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${YOUR_DOMAIN_NAME}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SHELL_SSH_PORT}
        gitlab_rails['time_zone'] = '${TIME_ZONE}'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['gitlab_email_from'] = '${SMTP_USER_NAME}'
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_user_name'] = "${SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_tls'] = true
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 2
        nginx['enable'] = true
        nginx['listen_addresses'] = ["0.0.0.0"]
        nginx['listen_port'] = 7000
        nginx['http2_enabled'] = true
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
    networks:
      frontend:
    restart: always
    container_name: gitlab
  
  nginx:
    depends_on:
      - gitlab
    # image: thinksvip/lnmp:nginx-alpine
    image: registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:nginx-alpine
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_CONF_PATH}conf.d/:/etc/nginx/conf.d/:ro,cached
      - ${NGINX_HOST_CONF_PATH}nginx.conf:/etc/nginx/nginx.conf:ro,cached
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx/:rw,cached
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      frontend:
    restart: always
    container_name: nginx

networks:
  frontend:
    name: custom_network
